### ISSUE TITLE
Please make a new release of svgcheck

### ISSUE THREAD

**Issue by dkg** [ietf-tools/svgcheck#1]
Thanks for all the work you've done recently getting svgcheck moved into git and cleaning up the project metadata and CI!

It would be great to make a new release, superceding 0.6.0, but pointing back to the updated project information.

I'm looking at putting svgcheck into debian to make it easier for folks to develop RFCs from debian and its derived operating systems, and having an updated release (even one that doesn't change much functionally) would be useful for that.

When you make the new release, please consider including the test data, because (as with https://github.com/ietf-tools/rfctools-common/issues/1) running standard tests on the current 0.6.0 module fails due to missing data.

**Comment by rjsparks** [comment]
We have several cleanup tasks to get this, and several related repositories, to a state where the CI we are targeting can actually work. In particular, see https://github.com/pypa/pypi-support/issues/1731.
Sometimes these requests get processed quickly, and sometimes they don't. If this doesn't get attention in a few days, we'll start steps to work around it.

**Comment by rjsparks** [comment]
Digging and thinking a bit further - is there an expectation that `python -m unittest discover` should work for all packages?

The current test environment expects tests to be run with tox (which takes care of the setup above). An alternate way to run the tests successfully is:
```
git clone (some svgcheck reference)
python3 -mvenv env; source env/bin/activate
pip install tox
tox -e py39-macos
```
or whatever python-platform you are testing on - choose from
```
envlist = py{27,36,37,38,39}-{linux,macos,windows}
```
at the moment.

**Comment by dkg** [comment]
hey there, it looks like v0.6.1 was tagged back in 2022-04-05, but it is not released on https://pypi.org/project/svgcheck/

as for the tests: i'd be fine with using `tox` for the tests if that's your preferred arrangement.  I'm not sure what you'd want me to do for platforms other than linux, macos, and windows (some obscure Debian ports don't use linux, but instead rely on the FreeBSD or HURD kernels, for example), but that can wait; getting svgcheck published cleanly on PyPI is probably a higher priority.
