### ISSUE TITLE
Have an article explain why conforming to SVG requirements is necessary

### ISSUE THREAD

**Issue by ooker777** [ietf-tools/svgcheck#38]
Not an issue but a suggestion. Perhaps you want to have an article explain:
- Why conforming to SVG requirements is necessary, 
- What common mistakes leading to it,
- How to prevent it to happen, and
- What to do when you have one

For most people they won't know about this. My malformed file is still readable by image viewers and browsers. Only when I [run script](https://github.com/squidfunk/mkdocs-material/issues/3250 "Social cards fail to use an svg logo · Issue #3250 · squidfunk/mkdocs-material") that it breaks. I try to repair with this tool but it doesn't work.

**Comment by rjsparks** [comment]
There is ongoing community discussion (now in the RSWG) about changing the restrictions we place on SVG. 

See the various threads at https://mailarchive.ietf.org/arch/browse/rswg/?q=svg.

If you haven't found it already, take a look at https://datatracker.ietf.org/doc/draft-carpenter-rswg-rfc7996-issues/
