### ISSUE TITLE
test skipped on everything but windows

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/svgcheck#4]
At https://github.com/ietf-tools/svgcheck/blob/main/svgcheck/test.py#L116 there is a strange skip:
```
    @unittest.skipIf(os.name != 'nt', "xi:include does not work correctly on Linux")
```
Please investigate and adapt the test to work cross-platform.

**Comment by kesara** [comment]
OBE. `xinclude` related manipulations have been removed from `v0.7.0`.
