### ISSUE TITLE
Only black and white as colors?

### ISSUE THREAD

**Issue by ValdemarOtte** [ietf-tools/svgcheck#41]
I have a SVG file with multiple different colors. After running `svgcheck` on the file I get the error:

`path\to\file.svg:21921: The attribute 'color' does not allow the value '#00ffff', replaced with 'black'`

Is it possible to keep the original color? Or can `svgcheck` only accept the values for black and white?

**Comment by kesara** [comment]
@ValdemarOtte `svgcheck` conforms with [draft-7996-bis-00](https://datatracker.ietf.org/doc/html/draft-7996-bis-00), so only black & white are allowed.

**Comment by ValdemarOtte** [comment]
Thanks for the fast reply!
