### ISSUE TITLE
Add support for newer python versions such as 3.12

### ISSUE THREAD

**Issue by dwaite** [ietf-tools/svgcheck#47]
There is an error a few are hitting upstream as recent svgcheck builds are built to forbid installation on newer python versions. This causes ancient versions of both svgcheck and dependencies to be used instead.

e.g. https://github.com/ietf-tools/rfctools-common/issues/12

I don't know the reasoning for restricting minor language versions, but it may not be having the desired effect. I would recommend either modifying the max language limitation or deleting all old svgcheck packages from pypi.

**Comment by dwaite** [comment]
I do realize that mainline added a patch to allow for python 3.12 two days ago (indeed, installing the package in this way was how I worked around the issue in my own environment).

However, it does not appear that other popular tooling used by IETF spec authors (like https://github.com/martinthomson/i-d-template) represent that there may be a multiple-month gap in supporting new python versions due to this library.

It certainly seems inappropriate that newer python versions should fail by pulling in extremely old, known-broken library versions instead of a recent, likely-working library version.

**Comment by kesara** [comment]
Thanks for the bug report.
It makes sense to remove the restriction of the newer Python versions.
